dist: bionic
language: rust
cache: cargo
env:
  global:
    - RUST_BACKTRACE=full
rust:
  - stable
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libdbus-1-dev
      - gnome-keyring
      - dbus-x11
      - libssl-dev
jobs:
  fast_finish: true
before_cache:
  - chmod -R a+r $HOME/.cargo

before_script:
  - git clone https://gitlab.gnome.org/GNOME/libsecret.git

before_install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy --release
  - ci/test.sh
branches:
  only:
    - master
