sudo: required
language: rust
cache: cargo

rust:
  - stable
  - 1.42.0
  - nightly

os:
  - osx
  - windows
  - linux

addons:
  apt:
    packages:
    - libdbus-1-dev # Linking fails without this

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

# Dependencies
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install cargo-travis || echo "cargo-travis already installed"

script:
  - cargo fmt -- --verbose --check
  - cargo build --verbose --release
  - cargo clippy --verbose --release -- --deny clippy
  - cargo test --verbose --release

before_deploy:
  - ci/package.sh

deploy:
  file_glob: true
  files: target/package/*
  on:
    rust: stable
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/ # release tags
