dist: bionic
language: rust
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS='-C link-arg=-s'
rust:
  - stable
  - nightly
os:
  - osx
  - windows
  - linux
addons:
  apt:
    packages:
      - libdbus-1-dev
      - dbus-x11
jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
before_install:
  - rustup component add rustfmt || cargo install --git https://github.com/rust-lang/rustfmt/ --force rustfmt-nightly
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo fmt -- --check
  - cargo clippy --release
  - cargo test --release
branches:
  only:
    - master
