environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: crowbar
  matrix:
    - TARGET: x86_64-pc-windows-msvc
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
test_script:
  - cargo test --target %TARGET% --release
cache:
  - C:\Users\appveyor\.cargo\registry
  - target
branches:
  only:
    - master
notifications:
  - provider: Email
    on_build_success: false
build: false
