[package]
name = "oktaws"
version = "0.10.1"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."

[dependencies]
reqwest = "0.8"
serde = "1"
serde_derive = "1"
serde_str = "0.1"
toml = "0.4"
rusoto_core = "0.32"
rusoto_sts = "0.32"
rusoto_credential = "0.11"
base64 = "0.9"
structopt = "0.2"
structopt-derive = "0.2"
failure = "0.1"
log = "0.4"
stderrlog = "0.4"
keyring = "0.6"
username = "0.2"
dialoguer = "0.1"
sxd-document = "0.2"
sxd-xpath = "0.4"
kuchiki = "0.7"
regex = "1"
serde_ini = "0.1"
path_abs = "0.4"
rpassword = "2"
try_from = "0.2"
glob = "0.2"
walkdir = "2"
serde_json = "1"

[patch.crates-io]
# For https://github.com/servo/html5ever/pull/322
html5ever = { git = 'https://github.com/servo/html5ever', rev = '3d5e24bbc3ebadf4e1bb9a4e25dc24c80fed1670' }
# For https://github.com/rusoto/rusoto/pull/1001
rusoto_core = { git = 'https://github.com/rusoto/rusoto' }
# To support rusoto_core above
rusoto_credential = { git = 'https://github.com/rusoto/rusoto' }

[dev-dependencies]
tempfile = "3"
