[cook]
target_directory = "target/debug"
hashes = ["md5", "sha256", "sha512"]
containers = ["tar.bzip2"]
cook_directory = "target/cooked/"

[[cook.ingredient]]
source = "README.md"
destination = "README.md"
